"use client";

import { useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { parseClaudeCodeData } from "@/lib/parser";
import { parseCcusageJson } from "@/lib/ccusage-parser";
import { parseCcusageDailyJson } from "@/lib/ccusage-daily-parser";

export default function UploadPage() {
  const [isDragging, setIsDragging] = useState(false);
  const [selectedTool, setSelectedTool] = useState<string>("claude-code");
  const [files, setFiles] = useState<File[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const router = useRouter();

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const droppedFiles = Array.from(e.dataTransfer.files);
    const validFiles = droppedFiles.filter(
      (file) => file.name.endsWith(".json")
    );

    if (validFiles.length > 0) {
      setFiles(validFiles);
    }
  }, []);

  const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const selectedFiles = Array.from(e.target.files);
      setFiles(selectedFiles);
    }
  }, []);

  const handleProcess = async () => {
    if (files.length === 0) return;

    setIsProcessing(true);

    try {
      if (files.length > 1) {
        alert("Please upload only ONE JSON file generated by ccusage.");
        setIsProcessing(false);
        return;
      }

      const file = files[0];
      console.log(`Processing file: ${file.name}`);
      const text = await file.text();

      // Parse the JSON
      let jsonData;
      try {
        jsonData = JSON.parse(text);
      } catch (error) {
        alert("Invalid JSON file. Please make sure you're uploading the output from 'npx ccusage year --format json'");
        setIsProcessing(false);
        return;
      }

      // Check if it's ccusage daily JSON format
      if (jsonData.daily && jsonData.totals) {
        console.log("Detected ccusage daily JSON format");
        const stats = parseCcusageDailyJson(jsonData);

        // Store the stats
        sessionStorage.setItem("wrappedStats", JSON.stringify(stats));
        sessionStorage.setItem("selectedTool", selectedTool);

        console.log("Navigating to wrapped page with stats:", stats);
        router.push("/wrapped");
      }
      // Check if it's ccusage year JSON format (future)
      else if (jsonData.year && jsonData.stats) {
        console.log("Detected ccusage year JSON format");
        const stats = parseCcusageJson(jsonData);

        // Store the stats
        sessionStorage.setItem("wrappedStats", JSON.stringify(stats));
        sessionStorage.setItem("selectedTool", selectedTool);

        console.log("Navigating to wrapped page with stats:", stats);
        router.push("/wrapped");
      } else {
        alert("This doesn't look like a ccusage JSON file. Please run the command shown below and upload that file.");
        setIsProcessing(false);
      }
    } catch (error) {
      console.error("Error processing files:", error);
      alert(`Error processing file: ${error instanceof Error ? error.message : 'Unknown error'}. Check console for details.`);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white">
      {/* Header */}
      <header className="border-b border-gray-800">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <Link href="/">
            <h1 className="text-2xl font-bold bg-gradient-to-r from-orange-400 to-pink-600 text-transparent bg-clip-text cursor-pointer">
              VibeWrapped
            </h1>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-6 py-12 max-w-4xl">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Create Your Wrapped
          </h1>
          <p className="text-xl text-gray-400">
            Upload your AI coding tool data and get beautiful insights
          </p>
        </div>

        {/* Tool Selection */}
        <div className="mb-8">
          <label className="block text-lg font-semibold mb-4">
            Select Your AI Coding Tool
          </label>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { id: "claude-code", name: "Claude Code", icon: "🤖" },
              { id: "cursor", name: "Cursor", icon: "📝" },
              { id: "copilot", name: "Copilot", icon: "🚁" },
              { id: "windsurf", name: "Windsurf", icon: "🏄" },
            ].map((tool) => (
              <button
                key={tool.id}
                onClick={() => setSelectedTool(tool.id)}
                className={`p-4 rounded-lg border-2 transition-all ${
                  selectedTool === tool.id
                    ? "border-orange-500 bg-orange-500/10"
                    : "border-gray-700 hover:border-orange-500/50"
                }`}
              >
                <div className="text-3xl mb-2">{tool.icon}</div>
                <div className="font-semibold">{tool.name}</div>
              </button>
            ))}
          </div>
        </div>

        {/* File Upload */}
        <div className="mb-8">
          <label className="block text-lg font-semibold mb-4">
            Upload Your Data Files
          </label>

          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={`border-2 border-dashed rounded-lg p-12 text-center transition-all cursor-pointer ${
              isDragging
                ? "border-orange-500 bg-orange-500/10"
                : "border-gray-700 hover:border-orange-500/50"
            }`}
            onClick={() => document.getElementById("file-input")?.click()}
          >
            <input
              id="file-input"
              type="file"
              accept=".json"
              onChange={handleFileInput}
              className="hidden"
            />

            <div className="text-6xl mb-4">📁</div>

            {files.length > 0 ? (
              <div>
                <p className="text-xl font-semibold text-orange-400 mb-2">
                  ✅ File selected: {files[0].name}
                </p>
              </div>
            ) : (
              <div>
                <p className="text-xl font-semibold mb-2">
                  Drag & drop your JSON file here
                </p>
                <p className="text-gray-400">or click to browse</p>
              </div>
            )}
          </div>

          {/* Instructions */}
          <div className="mt-6 p-6 rounded-lg bg-gray-800/50 border border-gray-700">
            <h3 className="font-semibold mb-4 text-orange-400 text-lg">
              🚀 Super Easy 2-Step Process:
            </h3>

            {selectedTool === "claude-code" && (
              <div className="space-y-6 text-sm">
                {/* Step 1 */}
                <div className="bg-gradient-to-r from-orange-500/10 to-pink-600/10 border border-orange-500/30 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-orange-500 flex items-center justify-center font-bold text-white">1</div>
                    <div className="flex-1">
                      <p className="font-bold text-white mb-3">Run this command in your terminal:</p>
                      <div className="bg-gray-900 rounded p-3 font-mono text-xs text-green-400 mb-2">
                        npx ccusage daily --since {new Date().getFullYear()}0101 --until {new Date().getFullYear()}1231 --json &gt; my-wrapped.json
                      </div>
                      <p className="text-gray-400 text-xs">
                        This will analyze your {new Date().getFullYear()} Claude Code usage and create a <code className="bg-gray-700 px-1 rounded">my-wrapped.json</code> file
                      </p>
                      <p className="text-gray-400 text-xs mt-2">
                        💡 <strong>Tip:</strong> For other years, change the dates: <code className="bg-gray-700 px-1 rounded">--since 20240101 --until 20241231</code>
                      </p>
                    </div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="bg-gradient-to-r from-blue-500/10 to-purple-600/10 border border-blue-500/30 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center font-bold text-white">2</div>
                    <div className="flex-1">
                      <p className="font-bold text-white mb-2">Upload the JSON file above ☝️</p>
                      <p className="text-gray-400 text-xs">
                        The file will be created in your current directory. Just drag and drop it above!
                      </p>
                    </div>
                  </div>
                </div>

                {/* Why this is better */}
                <div className="border-t border-gray-700 pt-4">
                  <p className="text-xs text-gray-500">
                    <strong>💡 Why this way?</strong> The ccusage CLI accurately processes your Claude Code session logs,
                    calculates costs, and aggregates all your usage data. We then transform that into a beautiful
                    wrapped report with insights and stats! ✨
                  </p>
                </div>
              </div>
            )}

            {selectedTool === "cursor" && (
              <div className="space-y-4 text-sm">
                <div>
                  <p className="font-semibold mb-2 text-white">🖥️ On macOS:</p>
                  <ol className="list-decimal list-inside space-y-2 text-gray-300 ml-2">
                    <li>Open <strong>Finder</strong></li>
                    <li>Press <kbd className="px-2 py-1 bg-gray-700 rounded">Cmd</kbd> + <kbd className="px-2 py-1 bg-gray-700 rounded">Shift</kbd> + <kbd className="px-2 py-1 bg-gray-700 rounded">G</kbd></li>
                    <li>Paste: <code className="bg-gray-900 px-2 py-1 rounded">~/.cursor/logs</code></li>
                    <li>Select ALL <code>.jsonl</code> files</li>
                  </ol>
                </div>
                <div className="border-t border-gray-700 pt-4">
                  <p className="font-semibold mb-2 text-white">🪟 On Windows:</p>
                  <ol className="list-decimal list-inside space-y-2 text-gray-300 ml-2">
                    <li>Open <strong>File Explorer</strong></li>
                    <li>Click the address bar</li>
                    <li>Paste: <code className="bg-gray-900 px-2 py-1 rounded">%USERPROFILE%\.cursor\logs</code></li>
                    <li>Select ALL <code>.jsonl</code> files</li>
                  </ol>
                </div>
              </div>
            )}

            {(selectedTool === "copilot" || selectedTool === "windsurf") && (
              <div className="text-gray-400">
                <p>Support for {selectedTool} coming soon! For now, please use Claude Code or Cursor.</p>
              </div>
            )}
          </div>
        </div>

        {/* Process Button */}
        <div className="text-center">
          <button
            onClick={handleProcess}
            disabled={files.length === 0 || isProcessing}
            className={`px-8 py-4 rounded-lg font-semibold text-lg transition-all ${
              files.length === 0 || isProcessing
                ? "bg-gray-700 text-gray-500 cursor-not-allowed"
                : "bg-gradient-to-r from-orange-500 to-pink-600 hover:from-orange-600 hover:to-pink-700 shadow-lg shadow-orange-500/50"
            }`}
          >
            {isProcessing ? "Processing..." : "Generate My Wrapped 🎉"}
          </button>
        </div>
      </main>
    </div>
  );
}
