"use client";

import { useState, useCallback } from "react";
import { useRouter, useParams } from "next/navigation";
import toast, { Toaster } from "react-hot-toast";
import { parseClaudeCodeData } from "@/lib/parser";
import { parseCcusageJson } from "@/lib/ccusage-parser";
import { parseCcusageDailyJson } from "@/lib/ccusage-daily-parser";

export default function UploadPage() {
  const [isDragging, setIsDragging] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [copiedCommand, setCopiedCommand] = useState<string | null>(null);
  const router = useRouter();
  const params = useParams();
  const year = params.year as string;

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const droppedFiles = Array.from(e.dataTransfer.files);
    const validFiles = droppedFiles.filter(
      (file) => file.name.endsWith(".json")
    );

    if (validFiles.length > 0) {
      setFiles(validFiles);
    }
  }, []);

  const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const selectedFiles = Array.from(e.target.files);
      setFiles(selectedFiles);
    }
  }, []);

  const copyCommand = useCallback((command: string, id: string) => {
    navigator.clipboard.writeText(command);
    setCopiedCommand(id);
    setTimeout(() => {
      setCopiedCommand(null);
    }, 2000);
  }, []);

  const handleProcess = async () => {
    if (files.length === 0) return;

    setIsProcessing(true);

    try {
      if (files.length > 1) {
        toast.error("Please upload only ONE JSON file generated by ccusage.", {
          style: {
            background: '#374151',
            color: '#fff',
            fontFamily: 'var(--font-jetbrains-mono)',
          },
        });
        setIsProcessing(false);
        return;
      }

      const file = files[0];
      console.log(`Processing file: ${file.name}`);
      const text = await file.text();

      // Parse the JSON
      let jsonData;
      try {
        jsonData = JSON.parse(text);
      } catch (error) {
        toast.error("Invalid JSON file. Please make sure you're uploading the output from 'npx ccusage daily --json'", {
          style: {
            background: '#374151',
            color: '#fff',
            fontFamily: 'var(--font-jetbrains-mono)',
          },
          duration: 5000,
        });
        setIsProcessing(false);
        return;
      }

      // Check if it's ccusage daily JSON format
      if (jsonData.daily && jsonData.totals) {
        console.log("Detected ccusage daily JSON format");
        const stats = parseCcusageDailyJson(jsonData);

        // Store the stats
        sessionStorage.setItem("wrappedStats", JSON.stringify(stats));
        sessionStorage.setItem("selectedTool", "claude-code");

        console.log("Navigating to report page with stats:", stats);
        router.push(`/${year}/report`);
      }
      // Check if it's ccusage year JSON format (future)
      else if (jsonData.year && jsonData.stats) {
        console.log("Detected ccusage year JSON format");
        const stats = parseCcusageJson(jsonData);

        // Store the stats
        sessionStorage.setItem("wrappedStats", JSON.stringify(stats));
        sessionStorage.setItem("selectedTool", "claude-code");

        console.log("Navigating to report page with stats:", stats);
        router.push(`/${year}/report`);
      } else {
        toast.error("This doesn't look like a ccusage JSON file. Please run the command shown below and upload that file.", {
          style: {
            background: '#374151',
            color: '#fff',
            fontFamily: 'var(--font-jetbrains-mono)',
          },
          duration: 5000,
        });
        setIsProcessing(false);
      }
    } catch (error) {
      console.error("Error processing files:", error);
      toast.error(`Error processing file: ${error instanceof Error ? error.message : 'Unknown error'}. Check console for details.`, {
        style: {
          background: '#374151',
          color: '#fff',
          fontFamily: 'var(--font-jetbrains-mono)',
        },
        duration: 6000,
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <>
      <Toaster
        position="top-center"
        toastOptions={{
          style: {
            minWidth: '390px',
            maxWidth: '650px',
          },
          error: {
            iconTheme: {
              primary: '#f97316',
              secondary: '#fff',
            },
          },
        }}
      />
      <div className="min-h-[calc(100vh-5rem)] bg-linear-to-br from-gray-900 via-gray-800 to-black text-white flex items-center justify-center overflow-y-auto">
        <main className="flex-1 flex items-center justify-center px-4 sm:px-6 py-8">
        <div className="w-full max-w-4xl">
          <div className="text-center mb-4 sm:mb-6">
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-2">
              Your wrapped report is{" "}
              <span className="bg-linear-to-br from-orange-400 to-pink-600 text-transparent bg-clip-text">
                one upload
              </span>{" "}
              away
            </h1>
          </div>

          {/* Instructions */}
          <div className="mb-4">
            {/* Compact Instructions */}
            <div className="mt-2 sm:mt-4 p-3 sm:p-4 rounded-lg bg-gray-800/50 border border-gray-700">
              <h3 className="font-semibold mb-2 sm:mb-3 text-orange-400 text-sm sm:text-base">
                📋 Quick Setup:
              </h3>

              <div className="space-y-2 sm:space-y-3 text-xs sm:text-sm">
                {/* Step 1 */}
                <div className="bg-gradient-to-r from-orange-500/10 to-pink-600/10 border border-orange-500/30 rounded-lg p-2 sm:p-3">
                  <div className="flex items-start gap-2">
                    <div className="flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 rounded-full bg-orange-500 flex items-center justify-center font-bold text-white text-[10px] sm:text-xs">1</div>
                    <div className="flex-1">
                      <p className="font-semibold text-white mb-1 sm:mb-2 text-xs sm:text-sm">Run this command in your terminal:</p>

                      {/* macOS/Linux */}
                      <div className="mb-1 sm:mb-2">
                        <p className="text-gray-400 text-[10px] sm:text-xs mb-1">🍎 <strong>macOS/Linux:</strong></p>
                        <div className="relative group">
                          <div className="bg-gray-900 rounded p-1.5 sm:p-2 pr-8 font-mono text-[10px] sm:text-xs text-green-400 overflow-x-auto">
                            npx -y ccusage@latest daily --since {year}0101 --until {year}1231 --json &gt; ~/Desktop/my-wrapped-{year}.json
                          </div>
                          <button
                            onClick={() => copyCommand(`npx -y ccusage@latest daily --since ${year}0101 --until ${year}1231 --json > ~/Desktop/my-wrapped-${year}.json`, 'mac')}
                            className="absolute right-2 top-1/2 -translate-y-1/2 p-1 hover:bg-gray-800 rounded transition-colors"
                            title="Copy command"
                          >
                            {copiedCommand === 'mac' ? (
                              <svg className="w-3.5 h-3.5 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                              </svg>
                            ) : (
                              <svg className="w-3.5 h-3.5 text-gray-400 group-hover:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>

                      {/* Windows */}
                      <div className="mb-1 sm:mb-2">
                        <p className="text-gray-400 text-[10px] sm:text-xs mb-1">🪟 <strong>Windows:</strong></p>
                        <div className="relative group">
                          <div className="bg-gray-900 rounded p-1.5 sm:p-2 pr-8 font-mono text-[10px] sm:text-xs text-green-400 overflow-x-auto">
                            npx -y ccusage@latest daily --since {year}0101 --until {year}1231 --json &gt; %USERPROFILE%\Desktop\my-wrapped-{year}.json
                          </div>
                          <button
                            onClick={() => copyCommand(`npx -y ccusage@latest daily --since ${year}0101 --until ${year}1231 --json > %USERPROFILE%\\Desktop\\my-wrapped-${year}.json`, 'windows')}
                            className="absolute right-2 top-1/2 -translate-y-1/2 p-1 hover:bg-gray-800 rounded transition-colors"
                            title="Copy command"
                          >
                            {copiedCommand === 'windows' ? (
                              <svg className="w-3.5 h-3.5 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                              </svg>
                            ) : (
                              <svg className="w-3.5 h-3.5 text-gray-400 group-hover:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>

                      <p className="text-gray-400 text-[10px] sm:text-xs">
                        📁 File saved to your <strong>Desktop</strong> as <code className="bg-gray-700 px-0.5 sm:px-1 rounded text-[10px] sm:text-xs">my-wrapped-{year}.json</code>
                      </p>
                    </div>
                  </div>
                </div>

                {/* Step 2 */}
                <div className="bg-gradient-to-r from-blue-500/10 to-purple-600/10 border border-blue-500/30 rounded-lg p-2 sm:p-3">
                  <div className="flex items-start gap-2">
                    <div className="flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 rounded-full bg-blue-500 flex items-center justify-center font-bold text-white text-[10px] sm:text-xs">2</div>
                    <div className="flex-1">
                      <p className="font-semibold text-white mb-1 sm:mb-2 text-xs sm:text-sm">Upload your JSON file:</p>
                      <div
                        onDragOver={handleDragOver}
                        onDragLeave={handleDragLeave}
                        onDrop={handleDrop}
                        className={`border-2 border-dashed rounded-lg p-6 sm:p-8 md:p-10 text-center transition-all cursor-pointer ${
                          isDragging
                            ? "border-blue-400 bg-blue-500/10"
                            : "border-gray-600 hover:border-blue-400/50"
                        }`}
                        onClick={() => document.getElementById("file-input-2")?.click()}
                      >
                        <input
                          id="file-input-2"
                          type="file"
                          accept=".json"
                          onChange={handleFileInput}
                          className="hidden"
                        />

                        {files.length > 0 ? (
                          <div>
                            <div className="text-xl sm:text-2xl mb-1">✅</div>
                            <p className="text-xs sm:text-sm font-semibold mb-0.5">
                              {files[0].name}
                            </p>
                            <p className="text-[10px] sm:text-xs text-gray-400">Click to change file</p>
                          </div>
                        ) : (
                          <div>
                            <div className="text-xl sm:text-2xl mb-1">📁</div>
                            <p className="text-xs sm:text-sm font-semibold mb-0.5">
                              Drag & drop here
                            </p>
                            <p className="text-[10px] sm:text-xs text-gray-400">or click to browse</p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Process Button */}
          <div className="text-center">
            <button
              onClick={handleProcess}
              disabled={files.length === 0 || isProcessing}
              className={`px-10 py-4 rounded-xl font-semibold text-lg transition-all ${
                files.length === 0 || isProcessing
                  ? "bg-gray-700 text-gray-500 cursor-not-allowed"
                  : "bg-gradient-to-r from-orange-500 to-pink-600 hover:from-orange-600 hover:to-pink-700 shadow-lg shadow-orange-500/50 hover:scale-105 transform"
              }`}
            >
              {isProcessing ? "Processing..." : "Generate My Wrapped"}
            </button>
          </div>
        </div>
      </main>
      </div>
    </>
  );
}
