'use client'

import { useState, useCallback } from 'react'
import { useRouter, useParams, useSearchParams } from 'next/navigation'
import toast, { Toaster } from 'react-hot-toast'
import { parseCcusageJson } from '@/lib/ccusage-parser'
import { parseCcusageDailyJson } from '@/lib/ccusage-daily-parser'
import { fetchGitHubUserStats } from '@/lib/github-service'
import { parseGitHubStats } from '@/lib/github-parser'
import GitHubForm from '@/components/GitHubForm'

export default function UploadPage() {
  const searchParams = useSearchParams()
  const [activeTab, setActiveTab] = useState<'claude-code' | 'github'>(
    (searchParams.get('tab') as 'claude-code' | 'github') || 'claude-code'
  )
  const [isDragging, setIsDragging] = useState(false)
  const [files, setFiles] = useState<File[]>([])
  const [isProcessing, setIsProcessing] = useState(false)
  const [copiedCommand, setCopiedCommand] = useState<string | null>(null)
  const [windowsShell, setWindowsShell] = useState<'powershell' | 'cmd'>(
    'powershell'
  )
  const [packageManager, setPackageManager] = useState<
    'npm' | 'yarn' | 'pnpm' | 'bun'
  >('npm')
  const [githubUsername, setGithubUsername] = useState('')
  const router = useRouter()
  const params = useParams()
  const year = params.year as string

  // Update URL when tab changes
  const handleTabChange = (tab: 'claude-code' | 'github') => {
    setActiveTab(tab)
    const newUrl = tab === 'github' ? `?tab=github` : ''
    window.history.pushState({}, '', `/${year}/upload${newUrl}`)
  }

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)

    const droppedFiles = Array.from(e.dataTransfer.files)
    const validFiles = droppedFiles.filter(file => file.name.endsWith('.json'))

    if (validFiles.length > 0) {
      setFiles(validFiles)
    }
  }, [])

  const handleFileInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files.length > 0) {
        const selectedFiles = Array.from(e.target.files)
        setFiles(selectedFiles)
      }
    },
    []
  )

  const copyCommand = useCallback((command: string, id: string) => {
    navigator.clipboard.writeText(command)
    setCopiedCommand(id)
    setTimeout(() => {
      setCopiedCommand(null)
    }, 2000)
  }, [])

  const getCommandPrefix = useCallback(() => {
    const commands = {
      npm: 'npx -y ccusage@latest',
      yarn: 'yarn dlx --quiet ccusage@latest',
      pnpm: 'pnpm dlx ccusage@latest',
      bun: 'bunx ccusage@latest',
    }
    return commands[packageManager]
  }, [packageManager])

  const handleProcess = async () => {
    setIsProcessing(true)

    try {
      if (activeTab === 'claude-code') {
        // Claude Code processing
        if (files.length === 0) return

        if (files.length > 1) {
          toast.error(
            'Please upload only ONE JSON file generated by ccusage.',
            {
              style: {
                background: '#374151',
                color: '#fff',
                fontFamily: 'var(--font-jetbrains-mono)',
              },
            }
          )
          setIsProcessing(false)
          return
        }

        const file = files[0]
        console.log(`Processing file: ${file.name}`)
        const text = await file.text()

        // Parse the JSON
        let jsonData
        try {
          jsonData = JSON.parse(text)
        } catch {
          toast.error(
            "Invalid JSON file. Please make sure you're uploading the output from 'npx ccusage daily --json' → Make sure you're uploading the file generated from step 1",
            {
              style: {
                background: '#374151',
                color: '#fff',
                fontFamily: 'var(--font-jetbrains-mono)',
              },
              duration: 5000,
            }
          )
          setIsProcessing(false)
          return
        }

        // Check if it's ccusage daily JSON format
        if (jsonData.daily && jsonData.totals) {
          console.log('Detected ccusage daily JSON format')
          const stats = parseCcusageDailyJson(jsonData)

          // Store the stats
          sessionStorage.setItem('wrappedStats', JSON.stringify(stats))
          sessionStorage.setItem('selectedTool', 'claude-code')
          sessionStorage.setItem('uploadTab', 'claude-code')

          console.log('Navigating to report page with stats:', stats)
          router.push(`/${year}/report`)
        }
        // Check if it's ccusage year JSON format (future)
        else if (jsonData.year && jsonData.stats) {
          console.log('Detected ccusage year JSON format')
          const stats = parseCcusageJson(jsonData)

          // Store the stats
          sessionStorage.setItem('wrappedStats', JSON.stringify(stats))
          sessionStorage.setItem('selectedTool', 'claude-code')
          sessionStorage.setItem('uploadTab', 'claude-code')

          console.log('Navigating to report page with stats:', stats)
          router.push(`/${year}/report`)
        } else {
          toast.error(
            "This doesn't look like a valid/ccusage JSON file.\nPlease run the command shown below and upload that file.",
            {
              style: {
                background: '#374151',
                color: '#fff',
                fontFamily: 'var(--font-jetbrains-mono)',
              },
              duration: 5000,
            }
          )
          setIsProcessing(false)
        }
      } else if (activeTab === 'github') {
        // GitHub processing
        if (githubUsername.trim() === '') return

        console.log(`Fetching GitHub stats for: ${githubUsername}`)

        try {
          const githubStats = await fetchGitHubUserStats(
            githubUsername.trim(),
            parseInt(year)
          )
          const stats = parseGitHubStats(githubStats)

          // Store the stats
          sessionStorage.setItem('wrappedStats', JSON.stringify(stats))
          sessionStorage.setItem('selectedTool', 'github')
          sessionStorage.setItem('uploadTab', 'github')
          sessionStorage.setItem('githubUsername', githubUsername.trim())

          console.log('Navigating to report page with GitHub stats:', stats)
          router.push(
            `/${year}/report?tab=github&username=${encodeURIComponent(githubUsername.trim())}`
          )
        } catch (error) {
          toast.dismiss('github-fetch')
          throw error
        }
      }
    } catch (error) {
      console.error('Error processing:', error)
      toast.error(
        `Error: ${error instanceof Error ? error.message : 'Unknown error'}. Please check the username and try again.`,
        {
          style: {
            background: '#374151',
            color: '#fff',
            fontFamily: 'var(--font-jetbrains-mono)',
          },
          duration: 6000,
        }
      )
    } finally {
      setIsProcessing(false)
    }
  }

  return (
    <>
      <Toaster
        position="top-center"
        containerStyle={{
          top: '4.8rem',
        }}
        toastOptions={{
          style: {
            minWidth: '390px',
            maxWidth: '650px',
          },
          error: {
            iconTheme: {
              primary: '#f97316',
              secondary: '#fff',
            },
          },
        }}
      />
      <div className="min-h-[calc(100vh-4rem)] md:min-h-[calc(100vh-5rem)] bg-linear-to-br from-gray-900 via-gray-800 to-black text-white flex items-start justify-center">
        <main className="flex-1 flex items-start justify-center px-2 sm:px-6 py-4">
          <div className="w-full max-w-4xl">
            <div className="text-center mb-4 sm:mb-6">
              <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-2">
                Your wrapped report is{' '}
                <span className="bg-linear-to-br from-orange-400 to-pink-600 text-transparent bg-clip-text transition-all duration-300">
                  {activeTab === 'github' ? 'one click' : 'one upload'}
                </span>{' '}
                away
              </h1>
            </div>

            {/* Tabs */}
            <div className="mb-6 flex justify-center">
              <div className="flex gap-1.5 p-1 bg-gray-900/80 rounded-lg border border-gray-700 inline-flex">
                <button
                  onClick={() => handleTabChange('claude-code')}
                  className={`flex items-center gap-2 px-4 py-2 text-xs sm:text-sm font-semibold rounded-md transition-all ${
                    activeTab === 'claude-code'
                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                  }`}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    className="w-4 h-4"
                    fill="currentColor"
                  >
                    <path d="M22.2819 9.8211C22.7935 10.7902 23.0621 11.8738 23.0621 13C23.0621 14.1262 22.7935 15.2098 22.2819 16.1789C21.1772 18.369 18.9684 19.8621 16.4379 19.8621C15.3117 19.8621 14.2281 19.5935 13.259 19.0819C12.0699 18.4503 11.1179 17.4699 10.5172 16.2962L3.7483 19.8621C3.33047 20.062 2.84158 19.8931 2.64171 19.4753C2.44184 19.0574 2.61067 18.5686 3.0285 18.3687L9.79738 14.8028C9.74158 14.5461 9.70175 14.2806 9.67967 14.0103H2.3103C1.8551 14.0103 1.4862 13.6414 1.4862 13.1862C1.4862 12.731 1.8551 12.3621 2.3103 12.3621H9.67967C9.70175 12.0918 9.74158 11.8263 9.79738 11.5696L3.0285 8.00373C2.61067 7.80386 2.44184 7.31497 2.64171 6.89714C2.84158 6.47931 3.33047 6.31048 3.7483 6.51035L10.5172 10.0762C11.1179 8.9025 12.0699 7.92208 13.259 7.29052C14.2281 6.77893 15.3117 6.51035 16.4379 6.51035C18.9684 6.51035 21.1772 8.00341 22.2819 10.1935V9.8211Z" />
                  </svg>
                  Claude Code
                </button>
                <button
                  onClick={() => handleTabChange('github')}
                  className={`flex items-center gap-2 px-4 py-2 text-xs sm:text-sm font-semibold rounded-md transition-all ${
                    activeTab === 'github'
                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                  }`}
                >
                  <svg
                    className="w-4 h-4"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      fillRule="evenodd"
                      d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                      clipRule="evenodd"
                    />
                  </svg>
                  GitHub
                </button>
              </div>
            </div>

            {/* Instructions */}
            <div className="mb-4">
              {activeTab === 'claude-code' && (
                <>
                  {/* Compact Instructions */}
                  <div className="mt-2 sm:mt-4 p-3 sm:p-4 rounded-lg bg-gray-800/50 border border-gray-700">
                    <h3 className="font-semibold mb-2 sm:mb-3 text-orange-400 text-sm sm:text-base">
                      📋 Quick Setup:
                    </h3>

                    <div className="space-y-2 sm:space-y-3 text-xs sm:text-sm">
                      {/* Step 1 */}
                      <div className="bg-gradient-to-r from-orange-500/10 to-pink-600/10 border border-orange-500/30 rounded-lg p-2 sm:p-3">
                        <div className="flex items-start gap-2">
                          <div className="flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 rounded-full bg-orange-500 flex items-center justify-center font-bold text-white text-[10px] sm:text-xs">
                            1
                          </div>
                          <div className="flex-1">
                            <p className="font-semibold text-white mb-1 sm:mb-2 text-xs sm:text-sm">
                              Run this command in your terminal:
                            </p>

                            {/* Package Manager Selector */}
                            <div className="mb-3 sm:mb-4">
                              <p className="text-gray-300 text-[10px] sm:text-xs mb-2">
                                📦{' '}
                                <strong className="text-white">
                                  Choose your package manager:
                                </strong>
                              </p>
                              <div className="flex gap-1 sm:gap-1.5 p-1 bg-gray-900/80 rounded-lg border border-gray-700 flex-wrap">
                                <button
                                  onClick={() => setPackageManager('npm')}
                                  className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                    packageManager === 'npm'
                                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                  }`}
                                >
                                  npm
                                </button>
                                <button
                                  onClick={() => setPackageManager('yarn')}
                                  className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                    packageManager === 'yarn'
                                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                  }`}
                                >
                                  yarn
                                </button>
                                <button
                                  onClick={() => setPackageManager('pnpm')}
                                  className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                    packageManager === 'pnpm'
                                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                  }`}
                                >
                                  pnpm
                                </button>
                                <button
                                  onClick={() => setPackageManager('bun')}
                                  className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                    packageManager === 'bun'
                                      ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                  }`}
                                >
                                  bun
                                </button>
                              </div>
                            </div>

                            {/* macOS/Linux */}
                            <div className="mb-1 sm:mb-2">
                              <p className="text-gray-400 text-[10px] sm:text-xs mb-1">
                                🍎 <strong>macOS/Linux:</strong>
                              </p>
                              <div className="relative group">
                                <div className="bg-gray-900 rounded p-1.5 sm:p-2 pr-8 font-mono text-[10px] sm:text-xs text-green-400 overflow-x-auto">
                                  {getCommandPrefix()} daily --since {year}0101
                                  --until {year}1231 --json &gt;
                                  ~/Desktop/my-wrapped-{year}.json
                                </div>
                                <button
                                  onClick={() =>
                                    copyCommand(
                                      `${getCommandPrefix()} daily --since ${year}0101 --until ${year}1231 --json > ~/Desktop/my-wrapped-${year}.json`,
                                      'mac'
                                    )
                                  }
                                  className="absolute right-2 top-1/2 -translate-y-1/2 p-1 hover:bg-gray-800 rounded transition-colors"
                                  title="Copy command"
                                >
                                  {copiedCommand === 'mac' ? (
                                    <svg
                                      className="w-3.5 h-3.5 text-green-400"
                                      fill="none"
                                      stroke="currentColor"
                                      viewBox="0 0 24 24"
                                    >
                                      <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M5 13l4 4L19 7"
                                      />
                                    </svg>
                                  ) : (
                                    <svg
                                      className="w-3.5 h-3.5 text-gray-400 group-hover:text-gray-300"
                                      fill="none"
                                      stroke="currentColor"
                                      viewBox="0 0 24 24"
                                    >
                                      <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                                      />
                                    </svg>
                                  )}
                                </button>
                              </div>
                            </div>

                            {/* Windows */}
                            <div className="mb-1 sm:mb-2">
                              <div className="flex items-center gap-2 sm:gap-3 mb-2">
                                <p className="text-gray-300 text-[10px] sm:text-xs">
                                  🪟{' '}
                                  <strong className="text-white">
                                    Windows:
                                  </strong>
                                </p>
                                <div className="flex gap-0.5 sm:gap-1 p-1 bg-gray-900/80 rounded-lg border border-gray-700">
                                  <button
                                    onClick={() =>
                                      setWindowsShell('powershell')
                                    }
                                    className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                      windowsShell === 'powershell'
                                        ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                        : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                    }`}
                                  >
                                    PowerShell
                                  </button>
                                  <button
                                    onClick={() => setWindowsShell('cmd')}
                                    className={`px-3 sm:px-4 py-1 sm:py-1.5 text-[10px] sm:text-xs font-semibold rounded-md transition-all ${
                                      windowsShell === 'cmd'
                                        ? 'bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600 text-white shadow-md'
                                        : 'text-gray-400 hover:text-white hover:bg-gray-800'
                                    }`}
                                  >
                                    CMD
                                  </button>
                                </div>
                              </div>
                              <div className="relative group">
                                <div className="bg-gray-900 rounded p-1.5 sm:p-2 pr-8 font-mono text-[10px] sm:text-xs text-green-400 overflow-x-auto">
                                  {windowsShell === 'powershell'
                                    ? `${getCommandPrefix()} daily --since ${year}0101 --until ${year}1231 --json > "$HOME\\Desktop\\my-wrapped-${year}.json"`
                                    : `${getCommandPrefix()} daily --since ${year}0101 --until ${year}1231 --json > "%USERPROFILE%\\Desktop\\my-wrapped-${year}.json"`}
                                </div>
                                <button
                                  onClick={() => {
                                    const cmd =
                                      windowsShell === 'powershell'
                                        ? `${getCommandPrefix()} daily --since ${year}0101 --until ${year}1231 --json > "$HOME\\Desktop\\my-wrapped-${year}.json"`
                                        : `${getCommandPrefix()} daily --since ${year}0101 --until ${year}1231 --json > "%USERPROFILE%\\Desktop\\my-wrapped-${year}.json"`
                                    copyCommand(cmd, `windows-${windowsShell}`)
                                  }}
                                  className="absolute right-2 top-1/2 -translate-y-1/2 p-1 hover:bg-gray-800 rounded transition-colors"
                                  title="Copy command"
                                >
                                  {copiedCommand ===
                                  `windows-${windowsShell}` ? (
                                    <svg
                                      className="w-3.5 h-3.5 text-green-400"
                                      fill="none"
                                      stroke="currentColor"
                                      viewBox="0 0 24 24"
                                    >
                                      <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M5 13l4 4L19 7"
                                      />
                                    </svg>
                                  ) : (
                                    <svg
                                      className="w-3.5 h-3.5 text-gray-400 group-hover:text-gray-300"
                                      fill="none"
                                      stroke="currentColor"
                                      viewBox="0 0 24 24"
                                    >
                                      <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                                      />
                                    </svg>
                                  )}
                                </button>
                              </div>
                            </div>

                            <p className="text-gray-400 text-[10px] sm:text-xs">
                              📁 File saved to your <strong>Desktop</strong> as{' '}
                              <code className="bg-gray-700 px-0.5 sm:px-1 rounded text-[10px] sm:text-xs">
                                my-wrapped-{year}.json
                              </code>
                            </p>
                          </div>
                        </div>
                      </div>

                      {/* Step 2 */}
                      <div className="bg-gradient-to-r from-blue-500/10 to-purple-600/10 border border-blue-500/30 rounded-lg p-2 sm:p-3">
                        <div className="flex items-start gap-2">
                          <div className="flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 rounded-full bg-blue-500 flex items-center justify-center font-bold text-white text-[10px] sm:text-xs">
                            2
                          </div>
                          <div className="flex-1">
                            <p className="font-semibold text-white mb-1 sm:mb-2 text-xs sm:text-sm">
                              Upload your JSON file:
                            </p>
                            <div
                              onDragOver={handleDragOver}
                              onDragLeave={handleDragLeave}
                              onDrop={handleDrop}
                              className={`border-2 border-dashed rounded-lg p-6 sm:p-8 md:p-10 text-center transition-all cursor-pointer ${
                                isDragging
                                  ? 'border-blue-400 bg-blue-500/10'
                                  : 'border-gray-600 hover:border-blue-400/50'
                              }`}
                              onClick={() =>
                                document.getElementById('file-input-2')?.click()
                              }
                            >
                              <input
                                id="file-input-2"
                                type="file"
                                accept=".json"
                                onChange={handleFileInput}
                                className="hidden"
                              />

                              {files.length > 0 ? (
                                <div>
                                  <div className="text-xl sm:text-2xl mb-1">
                                    ✅
                                  </div>
                                  <p className="text-xs sm:text-sm font-semibold mb-0.5">
                                    {files[0].name}
                                  </p>
                                  <p className="text-[10px] sm:text-xs text-gray-400">
                                    Click to change file
                                  </p>
                                </div>
                              ) : (
                                <div>
                                  <div className="text-xl sm:text-2xl mb-1">
                                    📁
                                  </div>
                                  <p className="text-xs sm:text-sm font-semibold mb-0.5">
                                    Drag & drop here
                                  </p>
                                  <p className="text-[10px] sm:text-xs text-gray-400">
                                    or click to browse
                                  </p>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </>
              )}

              {activeTab === 'github' && (
                <GitHubForm
                  githubUsername={githubUsername}
                  setGithubUsername={setGithubUsername}
                  onSubmit={handleProcess}
                />
              )}
            </div>

            {/* Process Button */}
            <div className="text-center">
              <button
                onClick={handleProcess}
                disabled={
                  (activeTab === 'claude-code' &&
                    (files.length === 0 || isProcessing)) ||
                  (activeTab === 'github' &&
                    (githubUsername.trim() === '' || isProcessing))
                }
                className={`px-10 py-4 rounded-xl font-semibold text-lg transition-all inline-flex items-center justify-center gap-2 ${
                  (activeTab === 'claude-code' &&
                    (files.length === 0 || isProcessing)) ||
                  (activeTab === 'github' &&
                    (githubUsername.trim() === '' || isProcessing))
                    ? 'bg-gray-700 text-gray-500 cursor-not-allowed'
                    : 'bg-gradient-to-r from-orange-500 to-pink-600 hover:from-orange-600 hover:to-pink-700 shadow-lg shadow-orange-500/50 hover:scale-105 transform'
                }`}
              >
                {isProcessing && (
                  <svg
                    className="animate-spin h-5 w-5"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                )}
                {isProcessing ? 'Processing...' : 'Generate My Wrapped'}
              </button>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}
